### ISSUE TITLE
About escorts refueling on (distant) planets

### ISSUE THREAD

**Issue by IntegratedQuantum** [finite-galaxy/finite-galaxy#20]
If the player is travelling to system which is outside the range of an escort ship, that escort will land on a planet for refueling. I think this refueling process takes to long. The player has to wait quite a while for an escort to refuel.

**Comment by IntegratedQuantum** [comment]
The refuel rate using ramscoops also is to slow in my opinion

**Comment by finite-galaxy** [comment]
Which ramscoops are you using? I equip my ships with four Wanderer ramscoops each and have no serious difficulty with travelling from one end of space to another.

**Comment by IntegratedQuantum** [comment]
I use one wanderer ramscoop and it takes 1min 20s to refuel 2270 units of fuel.

**Comment by finite-galaxy** [comment]
Keep in mind fuel gain from ramscoop is not constant, it depends on the stars in the system and your distance to them (see data/stars.txt file); in some systems ships can completely refuel within seconds, elsewhere it might take a minute or more.
