### ISSUE TITLE
"FW Southern Recon 1B"

### ISSUE THREAD

**Issue by IntegratedQuantum** [finite-galaxy/finite-galaxy#23]
This mission found in "missions_free_worlds_middle.txt" tells you to steal an electron turret. This is impossible with the new system that doesn't allow you to steal outfits.
Possible solutions:
1. Make another mission which maybe involves stealing the Electron Cannon/Turret from a Republic production plant.
2. Add the Electron Cannon/Turret to the cargo of those ships you were supposed to steal it from.

**Comment by finite-galaxy** [comment]
Actually it is possible, you just have to *capture* a ship now.

**Comment by IntegratedQuantum** [comment]
Yes, but in my opinion capturing is very compared to the way it was before because now you have to protect a ship that can be disabled with one shot while jumping through at least 3 systems.

**Comment by finite-galaxy** [comment]
Yes, the mission is somewhat more challenging to complete, but that's not necessarily a bad thing.
