### ISSUE TITLE
"FW Southern Battle 2"

### ISSUE THREAD

**Issue by IntegratedQuantum** [finite-galaxy/finite-galaxy#24]
The mission tells you to go and attack Rastaban, but the mission destination is in Delta Sagitarii which not only doesn't make sense as a destination after capturing a neighbouring system, but also it is impossible to do the mission without a jump drive with the given deadline of 3 days.
Maybe you meant to choose Dancer as destination?

**Comment by finite-galaxy** [comment]
Thank you for pointing this out; hopefully solved in 3fe24a736ffe058339009d6df163513f4e791b14.
