### ISSUE TITLE
Writing direction

### ISSUE THREAD

**Issue by finite-galaxy** [finite-galaxy/finite-galaxy#3]
Currently only left-to-right writing direction is possible. Some languages (e.g. Arabic) are typically written right-to-left. If this game is ever to be translated, other writing directions should be supported.

**Comment by finite-galaxy** [comment]
Actually supporting different writing directions (e.g. right-to-left instead of left-to-right) is an issue separate from Unicode.

**Comment by Fzzr** [comment]
So it is. That PR is still possibly a useful starting point for #2.

**Comment by finite-galaxy** [comment]
Done by 299ea085edf57448dd2ab0a83e4cd08fc88a1561
