### ISSUE TITLE
text in pop up is partly hidden

### ISSUE THREAD

**Issue by IntegratedQuantum** [finite-galaxy/finite-galaxy#36]
![screenshot from 2019-02-12 19-10-23](https://user-images.githubusercontent.com/43880493/52657869-e548d200-2ef9-11e9-8f2f-5c99a7ff1f19.png)

As you can see here the price(it actually is 25,015,731) along with some other text is partly hidden by "…" which is definitely not right.

**Comment by finite-galaxy** [comment]
This is problematic; there are truncation functions in Dialogue.cpp and WrappedText.cpp. 
Possibly part of the problem is Format.cpp currently inserts normal spaces as thousands separators; should be changed to ' ' narrow non-breaking spaces (U+202F).

**Comment by finite-galaxy** [comment]
Could you describe how to reproduce it?

**Comment by finite-galaxy** [comment]
Should be solved by d902b851bdbcc10f09b0499e3d2159ee3aec5c91.
