### ISSUE TITLE
Republic fleets in remnant territory(Pantica)

### ISSUE THREAD

**Issue by IntegratedQuantum** [finite-galaxy/finite-galaxy#38]
![screenshot from 2019-02-13 20-29-20](https://user-images.githubusercontent.com/43880493/52738113-35916400-2fce-11e9-93bc-708800c4379a.png)

As you can see there are republic ships in remnant territory.
This one might be hard to track. As specified in map.txt events.txt and fleets.txt there should be no republic ships.

**Comment by finite-galaxy** [comment]
Thank you for spotting and reporting this! Solved in 8fd97f379b4475d9ca65d5e9c53df2359bd89230
