### ISSUE TITLE
 Art request: four gun Harpy [Sparrow]

### ISSUE THREAD

**Issue by finite-galaxy** [finite-galaxy/finite-galaxy#39]
The Harpy [ES Sparrow] currently has two visible gun ports. However, I'd like to have a version with four. Because my Blender-skills are non-existent, I'd appreciate it if someone else could create a new ship sprite and thumbnail.

Original assets are located at https://drive.google.com/drive/folders/0B9aK8dG39P29bmNQZlQxZ0pBZEU

**Comment by finite-galaxy** [comment]
Mock-up:
![harpy_m@2x](https://user-images.githubusercontent.com/44258906/62730357-14ab4800-ba20-11e9-8c2c-cb059710c046.png)

**Comment by finite-galaxy** [comment]
Furthermore, it would be interesting if the Hag/Finch and Harpy/Sparrow would have only a single engine.
@beccabunny, are you willing to use your Blender skills to create updated sprites and thumbnails?

**Comment by beccabunny** [comment]
Sorry, but I'm alredy working on way too many projects at the moment

**Comment by finite-galaxy** [comment]
ce7d8b8b9b16fe90b1fc6acd12919456f797eb5c
